### ISSUE TITLE
I'm getting an error, please tell me how to fix it.

### ISSUE THREAD

**Issue by CHK-0000** [gaston-michel/transcribir-bateria#1] opened 2024-10-17 07:14 UTC
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ksl10\\AppData\\Local\\Temp\\tmpclv_o6ov.midi'

**Comment by gaston-michel** [comment] 2024-10-17 12:53
Thank you for pointing out the issue. It was caused by the MIDI file extension. I’ve updated the code to use .mid for Windows and .midi for Linux. 
This has now been fixed in the latest commit. Please pull the latest changes and let me know if everything works as expected.

**Closed as completed** 2024-10-23 09:23 UTC
